package com.huang.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.huang.bean.Student;
import com.huang.bean.ChildSubject;
import com.huang.bean.ParentSubject;
import com.huang.bean.Jindu;

import com.huang.dao.StudentDao;
import com.huang.dao.ChildSubjectDao;
import com.huang.dao.ParentSubjectDao;
import com.huang.dao.JinduDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig studentDaoConfig;
    private final DaoConfig childSubjectDaoConfig;
    private final DaoConfig parentSubjectDaoConfig;
    private final DaoConfig jinduDaoConfig;

    private final StudentDao studentDao;
    private final ChildSubjectDao childSubjectDao;
    private final ParentSubjectDao parentSubjectDao;
    private final JinduDao jinduDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        studentDaoConfig = daoConfigMap.get(StudentDao.class).clone();
        studentDaoConfig.initIdentityScope(type);

        childSubjectDaoConfig = daoConfigMap.get(ChildSubjectDao.class).clone();
        childSubjectDaoConfig.initIdentityScope(type);

        parentSubjectDaoConfig = daoConfigMap.get(ParentSubjectDao.class).clone();
        parentSubjectDaoConfig.initIdentityScope(type);

        jinduDaoConfig = daoConfigMap.get(JinduDao.class).clone();
        jinduDaoConfig.initIdentityScope(type);

        studentDao = new StudentDao(studentDaoConfig, this);
        childSubjectDao = new ChildSubjectDao(childSubjectDaoConfig, this);
        parentSubjectDao = new ParentSubjectDao(parentSubjectDaoConfig, this);
        jinduDao = new JinduDao(jinduDaoConfig, this);

        registerDao(Student.class, studentDao);
        registerDao(ChildSubject.class, childSubjectDao);
        registerDao(ParentSubject.class, parentSubjectDao);
        registerDao(Jindu.class, jinduDao);
    }
    
    public void clear() {
        studentDaoConfig.getIdentityScope().clear();
        childSubjectDaoConfig.getIdentityScope().clear();
        parentSubjectDaoConfig.getIdentityScope().clear();
        jinduDaoConfig.getIdentityScope().clear();
    }

    public StudentDao getStudentDao() {
        return studentDao;
    }

    public ChildSubjectDao getChildSubjectDao() {
        return childSubjectDao;
    }

    public ParentSubjectDao getParentSubjectDao() {
        return parentSubjectDao;
    }

    public JinduDao getJinduDao() {
        return jinduDao;
    }

}
